services:
  app:
    build: .
    container_name: bookstore-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: ThisIsASecretKeyForBookstoreProjectJwtAuthentication123456789
      APP_JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bookstore_data:/var/lib/postgresql/data

volumes:
  bookstore_data:
